<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php
    $customlogo = MAGE::helper('ThemeOptions')->getThemeOptions('customlogo');
    $mediaurl = MAGE::helper('ThemeOptions')->getThemeOptions('mediaurl');
?>
<header id="header">
    <div class="top-header-wrapper">
        <div class="container_12">
            <div class="grid_12">
                <?php echo $this->getChildHtml('currency') ?>
                <?php if($this->getChildHtml('currency') and $this->getChildHtml('store_language')){echo '<div class="switch-divider"></div>';} ?>
                <?php echo $this->getChildHtml('store_language') ?>
                <?php echo $this->getChildHtml('topLinks') ?>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="header-wrapper">
        <div class="container_12">
            <div class="grid_5 logo-box">
                <?php if ($customlogo['logo_status'] == 0): ?>
                    <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
                    <?php else:?>
                    <h1 class="logo"><strong><?php echo $customlogo['logo_alt']; ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $customlogo['logo_alt']; ?>" class="logo"><img src="<?php echo $mediaurl.$customlogo['logo']; ?>" alt="<?php echo $customlogo['logo_alt']; ?>" /></a></h1>
                <?php endif; ?>
            </div>
            <div class="grid_7 quick-access">
                <?php echo $this->getChildHtml('topCart') ?>
                <div class="clear"></div>
                <div class="right">
                    <?php echo $this->getChildHtml('topSearch') ?>
                    <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div class="grid_12">
                <?php echo $this->getChildHtml('topMenu') ?>
                <?php echo $this->getChildHtml('slides.all') ?>
                <?php echo $this->getChildHtml('topContainer'); ?>
            </div>
            <div class="clear"></div>
        </div>
    </div>    
</header>