<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
    
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Grid Mode ?>

<div class="meigee-widget">
    <?php 
    $i=0; foreach ($_productCollection as $_product):
    if($_product->isSaleable()): 
    ?>
    <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid">
    <?php endif ?>
        <li class="grid_3 item<?php if(($i-1)%$_columnCount==0): ?> first alpha<?php elseif($i%$_columnCount==0): ?> last omega<?php endif; ?>">
            <div class="grid-indent">
		<div class="product-box">
                    <div class="product-img-box">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(191, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 190); ?><?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?></a>
                        <a href="<?php echo $_product->getProductUrl() ?>" class="icon-product-details"></a>
                        <?php // Fancybox
                        if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
                            <a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
                        <?php endif; // End Fancybox ?>
                    </div>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>                        
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>                           
                    </div>
                </div>
            </div>
        </li>
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
    </ul>
    <?php endif ?>
    <?php endif; if ($i == $_collectionSize ) break; endforeach ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <script type="text/javascript">            
        jQuery(window).load(function() {
            var grids = $$('.products-grid');                
            grids.each(function(n){					
                var columns = n.select('li.item');					
                var max_height = 0;															
                columns.each(function(m){														
                    if( m.getHeight() >  max_height ){
                        max_height = m.getHeight();
                    }						
                });
                var boxes = n.select('li .product-box');
                boxes.each(function(b){			
                    var this_column = b.up('li.item');
                    var box_indent = this_column.getHeight() - b.getHeight();                        
                    b.setStyle({
                        height: max_height - box_indent + 'px'
                    });					
                 });
            });                
         });
    </script>
</div>