<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();

    $randId = rand (0, 9999);
    
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Slider ?>
<div class="home-slider-conainer">
    <div class="home-slider">
	<ul class="products-grid" id="home-slider-<?php echo $randId; ?>">
	    <?php 
            $i=0; foreach ($_productCollection as $_product):
             if($_product->isSaleable()): 
        ?>
		<li class="item grid_3">
		    <div class="grid-indent">
			<div class="product-box">
			    <div class="product-img-box">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(191, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 190); ?><?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?></a>
				<a href="<?php echo $_product->getProductUrl() ?>" class="icon-product-details"></a>
				<?php // Fancybox
				if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
				    <a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
				<?php endif; // End Fancybox ?>
			    </div>
			    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
			    <?php echo $this->getPriceHtml($_product, true) ?>
			    <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
			</div>
		    </div>
		</li>
	    <?php endif; if (++$i > $_collectionSize-1 ) break; endforeach ?>
	</ul>
    </div>
</div>
<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<script type="text/javascript">
  jQuery(window).load(function(){
    jQuery('#home-slider-<?php echo $randId; ?>').bxSlider({
        mode: 'horizontal',
        infiniteLoop: true,
        hideControlOnEnd: true,
        controls: true,
        auto: true,
        autoDelay: 5000,
        autoHover: true,
        pause: 5000,
        ticker: false,
        tickerSpeed: 1000,
        tickerDirection: 'next',
        tickerHover: false,
        pager: false
        <?php echo $this->getSliderOptions(); ?>
	});
  });
</script>