<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php 
    if($this->getItems()->getSize()):
    $productpage_collateral_related = MAGE::helper('ThemeOptions')->getThemeOptions('productpage_collateral_related'); 
?>
<div class="blocks-wrapper">
    <div class="inner-wrapper">    
        <div class="container_12">
            <div class="grid_12">
                <section class="block-related">
                    <header>
                        <h2><?php echo $this->__('Related Products') ?></h2>
                    </header>
                    <div class="block-content">
                        <p class="block-subtitle"><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllRelated(this); return false;"><?php echo $this->__('select all') ?></a></p>
                        <ul <?php if ($productpage_collateral_related == 'related_slider' && count($this->getItems())>4): ?>id="block-related-slider"<?php endif; ?>>
                        <?php $i=0; foreach($this->getItems() as $_item): ?>
                            <li class="item grid_3">                
                                <div class="grid-indent">
                                    <div class="product-box">
                                        <div class="product">
                                            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(191, null) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                                            <div class="product-details">
                                                <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                                                    <?php if (!$_item->getRequiredOptions()): ?>
                                                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                                                <br class="clear" />
                                                <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                    <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>                
                                </div>
                            </li>
                            <?php if ($productpage_collateral_related !== 'related_slider' && ($i+1)%4==0): ?><li class="clear"></li><?php endif; ?>
                        <?php $i++; endforeach ?>
                        </ul>
                    </div>
                    <script type="text/javascript">
                    //<![CDATA[
                    $$('.related-checkbox').each(function(elem){
                        Event.observe(elem, 'click', addRelatedToProduct)
                    });
                
                    var relatedProductsCheckFlag = false;
                    function selectAllRelated(txt){
                        if (relatedProductsCheckFlag == false) {
                            $$('.related-checkbox').each(function(elem){
                                elem.checked = true;
                            });
                            relatedProductsCheckFlag = true;
                            txt.innerHTML="<?php echo $this->__('unselect all') ?>";
                        } else {
                            $$('.related-checkbox').each(function(elem){
                                elem.checked = false;
                            });
                            relatedProductsCheckFlag = false;
                            txt.innerHTML="<?php echo $this->__('select all') ?>";
                        }
                        addRelatedToProduct();
                    }
                
                    function addRelatedToProduct(){
                        var checkboxes = $$('.related-checkbox');
                        var values = [];
                        for(var i=0;i<checkboxes.length;i++){
                            if(checkboxes[i].checked) values.push(checkboxes[i].value);
                        }
                        if($('related-products-field')){
                            $('related-products-field').value = values.join(',');
                        }
                    }
                    //]]>
                    </script>
                    <script type="text/javascript">            
                        jQuery(window).load(function() {
                            var grids = $$('#block-related-slider, .block-related');
                            grids.each(function(n){					
                                var columns = n.select('li.item');					
                                var max_height = 0;															
                                columns.each(function(m){														
                                    if( m.getHeight() >  max_height ){
                                        max_height = m.getHeight();
                                    }						
                                });
                                var boxes = n.select('li .product-box');
                                boxes.each(function(b){			
                                    var this_column = b.up('li.item');
                                    var box_indent = this_column.getHeight() - b.getHeight();                        
                                    b.setStyle({
                                        height: max_height - box_indent + 'px'
                                    });					
                                 });
                            });                
                         });
                    </script>
                </section>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<?php endif ?>