<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 *
 *
 *
 * Template for Mage_Page_Block_Html
 */
?>
<?php 
/*****/
$sidebarPosition = MAGE::helper('ThemeOptions')->getThemeOptions('sidebar'); 
$custompatern = MAGE::helper('ThemeOptions')->getThemeOptions('custompatern');
if (!$custompatern):
    $bgPatern = MAGE::helper('ThemeOptions')->getThemeOptions('patern');
else:
    $mediaurl = MAGE::helper('ThemeOptions')->getThemeOptions('mediaurl');
    $paternurl = 'style="background:url('.$mediaurl.$custompatern.') center top repeat;"';
endif;
/*****/
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<div class="site-wrapper <?php echo $bgPatern ?><?php echo $paternurl; ?>">    
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('breadcrumbs') ?>
    <div class="main-container col1-layout">
        <div class="col-main">
            <?php echo $this->getChildHtml('global_messages') ?>
            <?php echo $this->getChildHtml('content') ?>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>